### ISSUE TITLE
まだボタン化されてない音源を作る

### ISSUE THREAD

**Issue by ndxbn** [sanabutton/sanabutton.github.io#2]
- [ ] https://www.youtube.com/watch?v=IW3b9uIn23I  ニューモデルだよ！全員集合！　#03
- [ ] https://www.youtube.com/watch?v=ON-mdAditJk  ニューモデルってなんだよ、カメラの質が良くなったんじゃない？雑談
- [ ] https://www.youtube.com/watch?v=YxHN6ivF3fo  【名取さな】お悩みドドンと解決！さなねる診療室【因幡はねる】
- [ ] https://www.youtube.com/watch?v=4Ix5vOKKrXQ  つよつよプレイですぐに終わらせるぞ！れいや～ずおぶふぃあ～！
- [ ] https://www.youtube.com/watch?v=yjiFUMhNOWw  名取さな、〇〇〇になるやつ告知します！
- [ ] https://www.youtube.com/watch?v=EHghZa4gO0A  バーチャルサナトリウムお嬢様部
- [ ] https://www.youtube.com/watch?v=-OLzHrKE_LA  まだ8月だぞ喋ろうぜ！

**Comment by ndxbn** [comment]
ボタンにするための元の音源はあるので、リファクタ終わったらすぐ着手するーー

1. 新しく音源追加
1. URL をばらまいて「ゆーらんさんが忙しくて更新できてなさそうなので、こっちで（勝手に）引き継いだ」宣言する

あと、 https://github.com/sanabutton/sanabutton.github.io/issues/6 を名取本人に相談するのも早めにやったほうが良さそう

**Comment by ndxbn** [comment]
> あと、 #6 を名取本人に相談するのも早めにやったほうが良さそう

#6 にも書いたのだけれど、「商用利用はダメ」と http://twpf.jp/sana_natori に書かれているので、名取本人に確認するまでもなくダメ。

**Comment by himanoa** [comment]
音声ファイル用のリポジトリを切ってそっちに移して、ビルド時に落としてくるようにする、とかだと維持コストかからなくて良いかもしれないです！

**Comment by ndxbn** [comment]
音源作るの、1回分だけでも結構な労力になるので、それぞれで単体の issue にわけておきますね
