### ISSUE TITLE
「名取友達いたんだ」の件りのボタンがあるか確認するやつ

### ISSUE THREAD

**Issue by ndxbn** [sanabutton/sanabutton.github.io#238]
> コメ「名取友達いたんだ…」
> 名取「いやおるわ！一人でスプラやってたらやばいやつじゃん？」
> コメ「おれやばいやつだわ…」
> コメ「隠のモノ全員やばいな…」
> 名取「あーーーごめんちがうそういうつもりじゃなくて！、！」
> https://twitter.com/unit07_/status/1065077570658418688

> さなボタン録画から取ってるならありそう
> アーカイブから取ってるならないか
> https://twitter.com/unit07_/status/1065078019289534464

とのこと

**Comment by kanaeco** [comment]
アーカイブでカットされた部分ですかね？
カット入った後のアーカイブを編集したので、その部分はボタン化してないですね
一応カット編集入る前の音源も持ってはいるけど、名取の意向でカットされてる部分なので無理に追加するのもどうかなって

**Comment by ndxbn** [comment]
なるほどね

カットされてるやつは追加しないっていう基本姿勢は同じなので、追加しなくていいかなって思います。

すまんこのやつは、その後に他の場所で言ってたりするし、無修正のやつが広く出回っており追加しなきゃっていう使命感でやった感じなので、例外かなって。

**Comment by ndxbn** [comment]
とりま、追加しない方針になったので、このIssueはクローズしますね
