### ISSUE TITLE
間違えて配信開始しちゃいたい芸のボタン、消したほうがいいか迷う

### ISSUE THREAD

**Issue by ndxbn** [sanabutton/sanabutton.github.io#377]
https://github.com/sanabutton/sanabutton.github.io/issues/223
間違えて配信開始しちゃいたい芸のボタン、消したほうがいいか迷う

カルテちゃんが引退されて、動画残ってないんだよねー

なとりの動画・配信であれば、なにか言われるまでは消さない の一択なのだけれど。

**Comment by ndxbn** [comment]
2019-04-16 以降にその時の意思決定をして、閉じる

**Comment by kanaeco** [comment]
個人的には残したいという気持ちがありますねー（あくまでも個人的感情であって明確な理由は無いです）
権利的にまずいとかならやむ無しですが…

**Comment by ndxbn** [comment]
今のところ、変わらず そのままでいいや の気持

**Comment by forno** [comment]
同じくそのままでいいかなという気持ち．
ここの認知もあるでしょうし，彼女が消えてなくなったわけではないので必要なら連絡が来るかなという気もします．
