### ISSUE TITLE
LINE スタンプに合わせて再生して楽しむために、使いやすい感じのやつを作る

### ISSUE THREAD

**Issue by ndxbn** [sanabutton/sanabutton.github.io#425]

**Comment by kanaeco** [comment]
おえかきカキカキでワロタｗ/おはようございナース

二マァ（該当なし） ※今日の配信で発言有り

3D名取のﾌﾆｬﾗｶｻｷﾞｮｰﾊｲｼﾝ/やっていくわよ
首の長さを修正したことを懺悔してみた/行くぜ！
名取がグリムエコーズするとこ見てて/行くぞー！

今日は9月31日/えーんえんえんおいおいおい

バイノーラルテスト配信/押し掛け

Let‘s GO！名取さな＃1/完全に理解した　※今日の配信で発言有り

首の長さを修正したことを懺悔してみた/何の話してたっけ

すこ/すこ04

3D名取のﾌﾆｬﾗｶｻｷﾞｮｰﾊｲｼﾝ/なで1

ハロウィンイベ蜜チューチューでワロタ/やっぴ～！

せんせえとないしょばなし/正解正解

首の長さを修正したことを懺悔してみた/ワイトもそう思います！
首の長さを修正したことを懺悔してみた/イリヤもそう思います！
ネコのさばきは突然にくる/僕もそう思いますにゃ

3D名取のﾎﾆｬﾎﾆｬﾄﾞﾛｰｲﾝｸﾞ/呼吸頑張ってる
3D名取のﾎﾆｬﾎﾆｬﾄﾞﾛｰｲﾝｸﾞ/呼吸を頑張ってみないかい

れいや～ずおぶふぃあ～Part4/了解！やります！

美術館/売り払ったベンツ　※今日の配信で発言有り

Let‘s GO！限界オタク＃2/いいね！2
４まんにんってなんまんにん？/偉すぎぃ！

めうから奪ったはんこでフェスやるめう。/キレちゃったね～

Let‘s GO！名取さな＃1/ミュートでオエッするナース　※今日の配信で発言有り

Let‘s GO！名取さな＃1/限界オタク8
6万人記念でホラゲ/息切れナース01
6万人記念でホラゲ/息切れナース02

つよつよPCチャレンジゲリラ/大変感謝しております

平成最後の配信だが礼はいらんゾｗってね/賢え〜1

毎年カップル板クリスマスコピペを見てブチ切れていた女の配信/メリークリスマス2

6万人記念でホラゲ/マ？02

登録者2万人達成で泣く名取/マ！？

なんでもないはなしをしよう/すまんな～
間違えて配信開始しちゃったよ芸/申し訳ございません

LINEすたんぷをつくるふぁむふぁたる/はい・・・

てね/てね03

平成最後の配信だが礼はいらんゾｗってね/フリーズしたハムスター

Let‘s GO！メスガキ四天王序列三位/もう許さねえからな

Let‘s GO！名取さな＃1/笑い声9　（てへ♡なぜか無かった）

ヒーラー職だからです/おつかれさな〜

**Comment by kanaeco** [comment]
雑にですが、使えそうなのまとめてみました（LINEスタンプ昇順）。
差し支えなければこの後の更新でボタン作ろうかと思います〜
