### ISSUE TITLE
jQuery やめたい

### ISSUE THREAD

**Issue by ndxbn** [sanabutton/sanabutton.github.io#58]
#50 で jQuery のバージョンを上げたところ、Gootgle PageSpeed Insights のスコアがオレンジになってしまいました。

ブラウザで見ている限りだと、「処理が全部終わるまでの時間」も「ページのレンダリングが完了するまでの時間」も短くなっているので、正直意味がわかりませんでした。

現状、jQuery は scroll to top でのみ利用されているだけなので、そのためだけに jQuery を使うのはやめたいです。
「トップに戻る」だけならいいのですが、jQuery を使っている理由は「アニメーションさせたい」というだけなので、ここだけどうにかなれば、jQuery をやめられるはずです。
https://github.com/sanabutton/sanabutton.github.io/blob/62eb85bace0e083eb37b711602c010e1dbb24b5e/scroll.js#L3-L15

**Comment by ndxbn** [comment]
https://twitter.com/akameco/status/1040273844815253505

https://twitter.com/akameco/status/1040274518504337414

**Comment by ndxbn** [comment]
## 結論

2018-09-21 時点では、jQuery を外せなさそう。

- jQuery は smooth scroll の poly fill 用途に使用されている
- smooth scroll は CSSOM で代替可能
- CSSOM はまだ Working Draft なので使えない

依然として、 jQuery を使って animation する必要はありそう。

## smooth-scroll poly fill ライブラリについて

https://cdnjs.com/libraries/smooth-scroll は、[CSSOM の scrolling](https://drafts.csswg.org/cssom-view/#scrolling) が実装されているブラウザ上で動いている前提で、 [scroll-behavior の smooth scroll](https://drafts.csswg.org/cssom-view/#valdef-scroll-behavior-smooth)を簡単に設定するためのライブラリに見える。[コード内で普通に `window.scrollTo()` を使ってる](https://github.com/cferdinandi/smooth-scroll/blob/master/dist/smooth-scroll.polyfills.js#L543)し、コード読む感じだと「`window.scrollTo()` が実装されている前提で、ブラウザによって引数の省略がバグってたりするから、それを補完する Polyfill」らしい。

## CSSOM の実装状況について

Working Draft なので、使うなって話ではある。
一応、[CSSOM Scroll-behavior の実装状況](https://caniuse.com/#feat=css-scroll-behavior)を確認してみたdが、見る限りだと、スマートフォンのデフォルトのブラウザ と Edge がまだ。

「CSSOM の API が生えているかどうか」は（おそらく）完全にブラウザ側の実装状況に委ねられているので、polyfill とかでなんとかできる範疇ではないと思う。

**Comment by ndxbn** [comment]
https://github.com/iamdustan/smoothscroll

**Comment by ndxbn** [comment]
https://github.com/iamdustan/smoothscroll のコードを読んだのだけれど、良さそうだったので採用したい。

Android / iOS などのスマートフォンはサポート対象外に見えるけれど、実装で使われている[`requestAnimationFrame()` の実装状況](https://caniuse.com/#feat=requestanimationframe)を見る限りだと、動きそうに見える。

**Comment by himanoa** [comment]
WebViewで座標ズレる問題、今やったら再現しなかったのと中身モバイルChromeっぽいので考えなくて良いです

**Comment by ndxbn** [comment]
iPad の chrome と safari  は動作確認しました。大丈夫そう。
