### ISSUE TITLE
ライセンスを CC にしたほうが良い？

### ISSUE THREAD

**Issue by ndxbn** [sanabutton/sanabutton.github.io#6]
でも、VTuber さん方は動画のライセンスを CC by 3.0 にしていなさそうだし、名取さなも現状はしてなさそう。

CC にしてくれたら、このリポジトリのライセンスも CC by 3.0 に緩めるーー

**Comment by ndxbn** [comment]
https://github.com/sanabutton/sanabutton.github.io/pull/43

**Comment by ndxbn** [comment]
「商用利用はダメ」と http://twpf.jp/sana_natori に書かれているので、しばらくは OSS ライセンスにできなさそう。

音声ファイルをどっかに逃がせば、コード自体は OSS ライセンスにできるので、そうする

**Comment by himanoa** [comment]
音声ファイル用のリポジトリを切ってそっちに移して、ビルド時に落としてくるようにする、とかだと維持コストかからなくて良いかもしれないです！

**Comment by ndxbn** [comment]
> 音声ファイル用のリポジトリ
なるほど

ビルドプロセスは特に手を入れるつもりがないので、「ビルド時に落としてくる」はできなさそうだけれど。
音声ファイル用の GitHub pages のリポジトリを作って、そこに別のドメインかパスを与えれば済みそうですねーー！！例えば sounds ってリポジトリを作って、https://sanabutton.love/sounds でアクセスできれば良い、という感じだと思うので、やってみます

**Comment by ndxbn** [comment]
中長期的に見た場合だと、容量の問題があると思ってるのですが、しばらくは大丈夫…かな…？

前に git lfs を使おうと思ったのだけれど、GitHub Pages との相性が悪かったのか、なんかちゃんとアクセスできなかったのだけれど、もう一回試してみるのもありかなって思った。
