### ISSUE TITLE
『名取さなとエドワード・ゴーリーの絵本を読もう』のボタンを作る？

### ISSUE THREAD

**Issue by kanaeco** [sanabutton/sanabutton.github.io#661]
https://live2.nicovideo.jp/watch/lv326395698

・そもそもニコ生って切り抜いて大丈夫？
・朗読パートは著作権的に無理そう
・有料パートは切り抜かない
→メインはセリフリクの切り抜きになりそう

**Comment by ndxbn** [comment]
ニコ生の切り抜き自体はやっていいですよ
怒られたら消す

> メインはセリフリクの切り抜きになりそう

同意。

**Comment by kanaeco** [comment]
>ニコ生の切り抜き自体はやっていいですよ
怒られたら消す

了解です。
とりあえず生放送が終わったらセリフリクパートだけで纏めてみようと思います。
（尤も他に配信ストックがあるので後回しになるかもですが・・・）

**Comment by kanaeco** [comment]
まさかのセリフリクが有料パートだったので、切り抜ける箇所ナシ！
