### ISSUE TITLE
開発環境の作り方・開発の手順 みたいなのを書く

### ISSUE THREAD

**Issue by ndxbn** [sanabutton/sanabutton.github.io#70]
after https://github.com/sanabutton/sanabutton.github.io/issues/69

開発環境の作り方でかくもの

- 必要な環境
- dokcer-compose.yml
- sounds を追加したい人は、どうすればよいか

**Comment by ndxbn** [comment]
せっかくなので、下書き感覚で書くわ

### Docker が使える環境の人

Mac とか Linux とか Windows 10 Pro の人向け。

```
git clone git@github.com:sanabutton/sanabutton.github.io.git
cd sanabutton.github.io
git clone git@github.com:sanabutton/sounds.git

docker-compose run
```

### Docker が使えない人

要するに、Windows 7 や Windows 10 Home の人向け。

#### 直上で動かしたい場合

#### Vagrant & Oracle Virtual Box で良い場合


`jekyll serve` コマンドが WEBrick を使っているせいで、sounds があるとどうにもならなくなってしまう。（WEBrick が日本語の含まれるパスを扱えないので。）


- Ruby
- 

```
git clone git@github.com:sanabutton/sanabutton.github.io.git
cd sanabutton.github.io
git clone git@github.com:sanabutton/sounds.git

```

**Comment by himanoa** [comment]
Python入ってる環境なら `python -m http.server` とかやるとカレントディレクトリを対象に雑にwebserverが立つのでそれでいいのでは(ただしWindowsはデフォルトでPython入ってないので別途入れてもらう必要がある)

**Comment by ndxbn** [comment]
https://qiita.com/sudahiroshi/items/e74d61d939f18779970d#rubysinatra%E7%B7%A8
Ruby でワンライナーで Web サーバを立てるのに、 sinatra を使うっていう選択肢があったので、それを試してみた。
よさげなので、これにしようかな…

**Comment by ndxbn** [comment]
Docker を使わないパターンのときなのだけれど。
sounds を提供する Web サーバを立てて、さなボタン(2)本体は _site/index.html をブラウザで直接開けばいいのでは…？って気がした。

**Comment by ndxbn** [comment]
https://github.com/sanabutton/sanabutton.github.io/wiki/%E3%81%95%E3%81%AA%E3%83%9C%E3%82%BF%E3%83%B3(2)%E3%81%AE%E6%A7%8B%E6%88%90 がすでにあるので、Close。
