### ISSUE TITLE
免許合宿WAO! のボタンがほしいです

### ISSUE THREAD

**Issue by kyontan** [sanabutton/sanabutton.github.io#825]
突然のIssue失礼します。
以前、表題のCMの声真似をしていた回がどこかにあったと記憶しているのですが、その回が思い出せず、ボタンでも見当たりませんでした。
もし可能であれば、追加していただけましたら幸いです。

**Comment by kanaeco** [comment]
多分この回と
https://youtu.be/MDlMFtEf0kA?t=3340s

この回だと思います。
https://youtu.be/BQWK8QdY5Dc?t=2180s

次回更新時に追加しようと思います〜

**Comment by kanaeco** [comment]
後者はそもそもボタン化してないのでまずそこからですね…

**Comment by kyontan** [comment]
意味不明なissueにも関わらず対応して頂きありがとうございます。
後者の方を探しておりました。 (どの回か全く思い出せず……)
ボタン化、気長にお待ちしております。よろしくお願いいたします。
