### ISSUE TITLE
も、Jekyllでビルドするのやめよっかな。もう、Jekyllでビルドやめちゃおっかなぁ~。グローバル汚染とかさぁそんな酷いことやるとかさ。もう折角さぁ…Contributeしようと思ってたのにさぁ

### ISSUE THREAD

**Issue by himanoa** [sanabutton/sanabutton.github.io#92]
Jekyll、JavaScript的親和性がないので、外部ライブラリ使いたい場合にindex.htmlが肥大化したりしてしんどいので ビルドスタックをnpm + babel + (任意のJSフレームワーク(React or Vue)) +  ESModules の構成にしたい。

以下に変わらないこととメリデメとESModulesを使う場合のモジュールバンドラをの選択肢を挙げる

### テンプレートエンジン特有の表現力

- 各所で使われている include といった別のファイルのテンプレートを展開するみたいな芸当はReactとモジュールバンドラを組み合わせることで欠如することなく表現できる(むしろJSが書けるので表現力あがるのでは)

### 外部ライブラリを探す時にCDNがあるかを探さなくて良い
   - `npm install` だけで完結する

### 名前空間の衝突やロードオーダーに気を使わなくてよい

- ES Modulesを使う場合はJavaScript毎に使うライブラリをimportすればファイル毎に名前空間を生成するため、治安の悪いライブラリを使わない限り気にしなくてよい

### 開発環境のセットアップ簡易化

静的htmlをビルドしてserveするみたいなのもNodejsがあればいいので開発環境に必要な処理系がシンプルになる

例えとして、webpack(モジュールバンドラ)を使う場合は`NODE_ENV=production npm run build` だけでリソースのビルドができる。

また、webpack-dev-serverを使えば、`npm run watch` をするだけでhttpserverが立ち上がり便利なだけではなく、ファイルの変更を検知してブラウザを自動でリロードするなども可能

## JavaScript書くために文法が過去のブラウザを気にしなくてよくなる

- babelを使うと未来の文法を使ってもES5に変換されるので過去に縛られずに幸せになれる。

## デメリット

- 任意のJSフレームワークの学習が必要
- 一枚のページの面倒を見るにはいいが将来的に複数ページの分岐をしようと思った時にコツが必要
  - gatsbyなりでなんとかなる

## モジュールバンドラ

使ったことあるやつだけ列挙してそれぞれメリデメを出す。
どれを使っても以下の機能は担保できる

- ファイル変更検知によりブラウザの自動リロード
- http serverをワンコマンドで立ち上げる
- babelを組み込むことができる

#### メリット

- 拡張によって複雑なことがやりやすい
  - ビルド時に https://github.com/sanabutton/sounds のファイルを舐めてbuttonとカテゴリヲファイル名から自動生成など

#### デメリット

- 拡張によって複雑なことがやりやすい
  - configファイルが秘伝化
  - webpack前提としたコードが発生して将来モジュールバンドラ不要な世界になった時に切り離しにくい

#### メリット

ゼロコンフィグで動くのでconfigの管理をしなくていい

#### デメリット

複雑なことがしにくい

**Comment by himanoa** [comment]
ビルドスタックの簡易化という点では #70 と関係あるかも

**Comment by ndxbn** [comment]
Jekyll やめたいっていうのはわかる。
Jekyll やめると、master にマージされたときに Travis とかでビルドして （gh-pages ブランチに）push っていうデプロイフローになると思うのだけれど、そのデプロイフローをメンテし続けるのめんどくさいなーと思って、あえて JavaScript的親和性 を全部捨ててたりします。

当初は、外部ライブラリを使いたいって思うほどのものを実装するか？（反語）みたいなのもあったので、JavaScript 的親和性を捨てるって選択をすぐにできた。しかし、将来的に [美兎ボタン のように](http://tsukino-mito.extrem.ne.jp/)プレイキュー的なものを実装したりするのかも？ってところまで考えると、 JavaScript 的親和性を捨てるのはどうなんだって感じはある。

ということで、ビルドスタックを簡略化したいのはわかるし、賛成ではある。
のだけれど、デプロイフロー変える…？（CI サービスでビルドして push とかするの、マ？）（手動は当然、論外 なのだけれど。）

**Comment by ndxbn** [comment]
あと、（static な）ボタンが大量にあるっていう特性上、仮想DOM 系は避けたいなーって思ってる

**Comment by himanoa** [comment]
サイトの雰囲気を残したままJavaScriptをゴリゴリ使いたい場面はというと僕が考えてるのは以下の通りですね。
- ランダム再生機能
- ボタンの絞り込み
- キューイング
- ページにアクセスするとGithubAPI叩いて、https://github.com/sanabutton/sounds の構造を取ってきて自動でファイル名から構造をDOMに反映する
  - SoundsのPRがマージしてmasterに反映されたら、ページ自体にボタンが勝手に自動反映される様になる
  - こっちはアプリケーションの根幹が壊れた時にしか手を入れなくてよくなる

**Comment by ndxbn** [comment]
今後も際限なくボタンは増え続けるだろうけど、パフォーマンス大丈夫ならまぁいっか

**Comment by himanoa** [comment]
デプロイフローを自体を変えるつもりはなくて(つまり今迄通りhtmlをビルドしてgh-pagesにpush)
単純にフロー中で実行するコマンドが変わるイメージです

**Comment by ndxbn** [comment]
> デプロイフローを自体を変えるつもりはなくて(つまり今迄通りhtmlをビルドしてgh-pagesにpush)
> 単純にフロー中で実行するコマンドが変わるイメージです

これなら全然いいと思ってる範疇なので、大丈夫ですーー

今は master に merge して終わり（ gh-pages ブランチ使ってない）で、「フロー中で実行するコマンド」がそもそもないので…

**Comment by himanoa** [comment]
CIでビルドして勝手に反映されるのは余裕があればやりたいですね

**Comment by himanoa** [comment]
repositoryのパス構造からhttps://github.com/sanabutton/sanabutton.github.io/blob/development/_includes/contents.html を自動生成したかったが 「すこ」とか人間がどうしてもマッピングしないと行けない部分があるのか…

**Comment by ndxbn** [comment]
> CIでビルドして勝手に反映されるのは余裕があればやりたいですね

「JavaScriptをゴリゴリ使いたい」ってなって、ちゃんと JavaScript も build するようにするなら、「CI でビルドして勝手に反映される」ようにするまではやる前提かなって思ってたーー


> 「すこ」とか人間がどうしてもマッピングしないと行けない部分があるのか…

こ自動生成できるところはすればいいし、できないところは設定ファイルか何かで持っておけばいいと思ってるので、別にそれはいいんじゃないかな

ただ、contents.html を自動生成するには、repository のパス構造だけでなく、それぞれがいつの放送か？（＆いつ投稿された動画か？）というメタ情報も必要になるのーー

**Comment by himanoa** [comment]
いつの放送か？のメタ情報、どこで使うのかパッとイメージが付かないですね…

**Comment by ndxbn** [comment]
> いつの放送か？のメタ情報、どこで使うのかパッとイメージが付かないですね…

新しく追加されたボタンが、ページの下に追加されていってるのだけれど、ディレクトリ構造だけだとわからないので。
ディレクトリのソートをするために使うデータに使うの

**Comment by himanoa** [comment]
なるほど

**Comment by himanoa** [comment]
ページにアクセスされたらGitHubAPIでうまくやることを前提にするとディレクトリで配信日時を持つしか方法はなさそうですね…

**Comment by ndxbn** [comment]
sounds のディレクトリ名に配信日時を入れるのはしたくないかなーって思ってる。

そういうメタデータとかは、 sanabutton.github.io リポジトリ側で持っておきたいな、と。

**Comment by ndxbn** [comment]
そもそも、sounds は、いまは GitHub においてあるけれど容量的に厳しくなったときに、なにか別の CDN に移行することも視野に入れてるので、「GitHub API でー」とかはしたくないかな…

**Comment by himanoa** [comment]
なるほど。そういう思惑があるならGH APIに依存しない方がよさそうですね。

ただ個人的にはこのファイル弄るの大分大変そうなのでもうちょっと楽な形式なりで書きたい気持ちはありますね。 https://github.com/sanabutton/sanabutton.github.io/blob/master/_includes/contents.html

**Comment by himanoa** [comment]
メタデータ用のデカいJSONを置いてビルド時にhtmlに変換する構造作るのが良さそうですかね…

**Comment by ndxbn** [comment]
> ただ個人的にはこのファイル弄るの大分大変そうなのでもうちょっと楽な形式なりで書きたい気持ちはありますね。
>  https://github.com/sanabutton/sanabutton.github.io/blob/master/_includes/contents.html

それはそう。
で、自動生成を目論んで、 https://github.com/sanabutton/sanabutton.github.io/issues/3 っていうことを考えてた。

**Comment by himanoa** [comment]
話がわかったのでそれはjekyllのpostでやるで良くて、Jekyllを殺さないでいい気がしてきました
