### ISSUE TITLE
master にマージされた後に、CI サービスでビルドして gh-pages ブランチにデプロイするようにする

### ISSUE THREAD

**Issue by ndxbn** [sanabutton/sanabutton.github.io#97]
「（フロントエンドで）JavaScriptをゴリゴリ使いたい場面」で困るので。（例 https://github.com/sanabutton/sanabutton.github.io/issues/92#issuecomment-428710044 ）
専ら「index.js をビルドする」用途でしか使わないつもり。

現状、`develop` ブランチがあって git flow みたいになっているので、 `gh-pages` ブランチをリリースブランチと捉えれば、それが正解かなって思う。
「master にマージされたら、自動でビルドしてリリースをする」って話になるので。

**Comment by ndxbn** [comment]
https://docs.travis-ci.com/user/deployment/pages/

**Comment by akameco** [comment]
percelの導入は秒でできるので、とりあえずpercel入れて必要になったらwebpackに切り替えがコスト低そうです

**Comment by ndxbn** [comment]
んじゃ、とりま percel でやるね

**Comment by ndxbn** [comment]
https://github.com/sanabutton/sanabutton.github.io/pull/107 でフロントエンドのビルドのベースは作った（つもり）なので、一旦 WIP 外します。

現状、フロントエンドでビルドしないといけないような事案はまだ発生していないので、そうなったときにやる

**Comment by ndxbn** [comment]
昨日夜ご飯を食べてたときの話だと、ひまのあせんせえがデータ（sounds の一覧とか）がとれる API サーバを作る みたいな話になってた。

**Comment by ndxbn** [comment]
保留の理由は、フロント側のビルドをどうするかが決定しないから。

**Comment by ndxbn** [comment]
https://github.com/sanabutton/frontend/ に準備済み。
https://github.com/sanabutton/frontend/commit/b0b3b32c13514d645ec93ce39da76260dbf9767b
